export const INCREMENT_PRODUCT = 'INCREMENT_PRODUCT';
export const DECREMENT_PRODUCT = 'DECREMENT_PRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
